name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # 每天午夜运行
  workflow_dispatch:  # 允许手动触发

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: readme

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: J1angJJ
          svg_out_path: readme/resources/grid-snake.svg

      - name: Push to readme branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: readme
          build_dir: readme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}